/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/app/(website)/**/*.{js,ts,tsx,jsx}',
    './src/components/**/*.{ts,tsx,js,jsx}',
    './src/providers/**/*.{ts,tsx,js,jsx}',
    './src/layouts/**/*.{ts,tsx,js,jsx}',
    './src/icons/**/*.{ts,tsx,js,jsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'native-bg': 'rgb(var(--native-background), <alpha-value>)',
        'black-primary': 'rgb(var(--black-primary), <alpha-value>)',
        'black-secondary': 'rgb(var(--black-secondary), <alpha-value>)',
        'btn-primary': 'rgb(var(--button-background-primary), <alpha-value>)',
        'btn-secondary': 'rgb(var(--button-background-secondary), <alpha-value>)',
        'surf-primary': 'rgb(var(--surface-line-primary), <alpha-value>)',
        'card-border': 'rgb(var(--card-border), <alpha-value>)',
        'card-bg': 'rgb(var(--card-background), <alpha-value>)',
        'link-active': 'rgb(var(--link-active), <alpha-value>)',
        'text-active': 'rgb(var(--text-active), <alpha-value>)',
        darkBlue: 'hsl(217, 28%, 15%)',
        darkBlue1: 'hsl(218, 28%, 13%)',
        darkBlue2: 'hsl(216, 53%, 9%)',
        darkBlue3: ' hsl(219, 30%, 18%)',
        accentCyan: 'hsl(176, 68%, 64%)',
        accentBlue: 'hsl(198, 60%, 50%)',
        lightRed: 'hsl(0, 100%, 63%)',
        primaryLight: '#ecf3fe',
        primaryLightHover: '#e3edfd',
        primaryLightActive: '#c4d9fc',
        primaryNormal: '#4285f4',
        primaryNormalHover: '#3b78dc',
        primaryNormalActive: '#356ac3',
        primaryDark: '#3264b7',
        primaryDarkHover: '#285092',
        primaryDarkActive: '#1e3c6e',
        primaryDarker: '#172f55',
        secondaryLight: '#FAFCFF',
        secondaryLightHover: '#eaeff4',
        secondaryLightActive: '#D6DCE4',
        secondaryNormal: '#7395b5',
        secondaryNormalHover: '#6886a3',
        secondaryNormalActive: '#5c7791',
        secondaryDark: '#567088',
        secondaryDarkHover: '#45596d',
        secondaryDarkActive: '#344351',
        secondaryDarker: '#28343f',
        grayLight: '#eeeeef',
        grayLightHover: '#e5e5e7',
        grayLightActive: '#c9cacd',
        grayNormal: '#50545e',
        grayNormalHover: '#484c55',
        grayNormalActive: '#40434b',
        grayDark: '#3c3f47',
        grayDarkHover: '#303238',
        grayDarkActive: '#24262a',
        grayDarker: '#1c1d21',
        constructiveLight: '#e7f3eb',
        constructiveLightHover: '#dcede1',
        constructiveLightActive: '#b6d9c1',
        constructiveNormal: '#138636',
        constructiveNormalHover: '#117931',
        constructiveNormalActive: '#0f6b2b',
        constructiveDark: '#0e6529',
        constructiveDarkHover: '#0b5020',
        constructiveDarkActive: '#093c18',
        constructiveDarker: '#072f13',
        informationLight: '#edf1f8',
        informationLightHover: '#e4eaf5',
        informationLightActive: '#c7d5ea',
        informationNormal: '#4976ba',
        informationNormalHover: '#426aa7',
        informationNormalActive: '#3a5e95',
        informationDark: '#37598c',
        informationDarkHover: '#2c4770',
        informationDarkActive: '#213554',
        informationDarker: '#1a2941',
        warningLight: '#fff5e7',
        warningLightHover: '#fff0db',
        warningLightActive: '#ffe0b5',
        warningNormal: '#ff9b0f',
        warningNormalHover: '#e68c0e',
        warningNormalActive: '#cc7c0c',
        warningDark: '#bf740b',
        warningDarkHover: '#995d09',
        warningDarkActive: '#734607',
        warningDarker: '#593605',
        destructiveLight: '#fae8eb',
        destructiveLightHover: '#f7dce0',
        destructiveLightActive: '#eeb6bf',
        destructiveNormal: '#c91432',
        destructiveNormalHover: '#b5122d',
        destructiveNormalActive: '#a11028',
        destructiveDark: '#970f26',
        destructiveDarkHover: '#790c1e',
        destructiveDarkActive: '#5a0916',
        destructiveDarker: '#460712',
      },
      backgroundImage: (theme) => ({
        'logo-dark-mode': "url('/assets/icons/logo-dark-mode.svg')",
        'logo-light-mode': "url('/assets/icons/logo-light-mode.svg')",
        'header-dark-dashboard': "url('/assets/icons/header-dark-home.svg')",
        'header-light-dashboard': "url('/assets/icons/header-light-home.svg')",
        'header-dark-ads': "url('/assets/icons/header-dark-ads.svg')",
        'header-light-ads': "url('/assets/icons/header-light-ads.svg')",
        'header-dark-product': "url('/assets/icons/header-dark-product.svg')",
        'header-light-product': "url('/assets/icons/header-light-product.svg')",
        'header-dark-shop': "url('/assets/icons/header-dark-shop.svg')",
        'header-light-shop': "url('/assets/icons/header-light-shop.svg')",
        'header-dark-advertisers': "url('/assets/icons/header-dark-advertisers.svg')",
        'header-light-advertisers': "url('/assets/icons/header-light-advertisers.svg')",
        'header-dark-corner': "url('/assets/icons/header-dark-corner.svg')",
        'header-light-corner': "url('/assets/icons/header-light-corner.svg')",
        'header-submenu-dark-user': "url('/assets/icons/header-submenu-dark-user.svg')",
        'header-submenu-light-user': "url('/assets/icons/header-submenu-light-user.svg')",
        'header-submenu-dark-plan': "url('/assets/icons/header-submenu-dark-plan.svg')",
        'header-submenu-light-plan': "url('/assets/icons/header-submenu-light-plan.svg')",
        'header-submenu-dark-message': "url('/assets/icons/header-submenu-dark-message.svg')",
        'header-submenu-light-message': "url('/assets/icons/header-submenu-light-message.svg')",
        'header-submenu-dark-support': "url('/assets/icons/header-submenu-dark-support.svg')",
        'header-submenu-light-support': "url('/assets/icons/header-submenu-light-support.svg')",
        'header-submenu-dark-logout': "url('/assets/icons/header-submenu-dark-logout.svg')",
        'header-submenu-light-logout': "url('/assets/icons/header-submenu-light-logout.svg')",
        'header-nav-dark-menu': "url('/assets/icons/header-dark-submen.svg')",
        'header-nav-light-menu': "url('/assets/icons/header-light-submen.svg')",
        'item-light-play': "url('/assets/icons/dashboard-item-light-play.svg')",
        'item-dark-play': "url('/assets/icons/dashboard-item-dark-play.svg')",
        'item-light-chat': "url('/assets/icons/dashboard-item-light-chat.svg')",
        'item-dark-chat': "url('/assets/icons/dashboard-item-dark-chat.svg')",
        'item-light-share': "url('/assets/icons/dashboard-item-light-share.svg')",
        'item-dark-share': "url('/assets/icons/dashboard-item-dark-share.svg')",
        'item-light-logo': "url('/assets/icons/item-light-logo.svg')",
        'item-dark-logo': "url('/assets/icons/item-dark-logo.svg')",
        'item-dark-bookmark': "url('/assets/icons/item-dark-bookmark.svg')",
        'item-light-bookmark': "url('/assets/icons/item-light-bookmark.svg')",
        'item-dark-calendar': "url('/assets/icons/item-dark-calendar.svg')",
        'item-light-calendar': "url('/assets/icons/item-light-calendar.svg')",
        'item-dark-hand': "url('/assets/icons/item-dark-hand.svg')",
        'item-light-hand': "url('/assets/icons/item-light-hand.svg')",
        'item-light-chart': "url('/assets/icons/item-light-chart.svg')",
        'item-dark-chart': "url('/assets/icons/item-dark-chart.svg')",
        'tiktok-light': "url('/assets/icons/tiktok.svg')",
        'tiktok-dark': "url('/assets/icons/tiktok-dark.svg')",
        'sort-light': "url('/assets/icons/light-sort.svg')",
        'sort-dark': "url('/assets/icons/dark-sort.svg')",
        'game-light': "url('/assets/icons/light-game.svg')",
        'game-dark': "url('/assets/icons/dark-game.svg')",
        'commerce-light': "url('/assets/icons/light-commerce.svg')",
        'commerce-dark': "url('/assets/icons/dark-commerce.svg')",
        'shipping-light': "url('/assets/icons/light-shipping.svg')",
        'shipping-dark': "url('/assets/icons/dark-shipping.svg')",
        'filter-light': "url('/assets/icons/light-filter.svg')",
        'filter-dark': "url('/assets/icons/dark-filter.svg')",
        'woocommerce-light': "url('/assets/icons/light-woocommerce.svg')",
        'woocommerce-dark': "url('/assets/icons/dark-woocommerce.svg')",
        'square-light': "url('/assets/icons/light-square.svg')",
        'square-dark': "url('/assets/icons/dark-square.svg')",
        'shopify-light': "url('/assets/icons/light-shopify.svg')",
        'shopify-dark': "url('/assets/icons/dark-shopify.svg')",
        'cloud-light': "url('/assets/icons/light-cloud.svg')",
        'cloud-dark': "url('/assets/icons/dark-cloud.svg')",
        'download-light': "url('/assets/icons/light-download.svg')",
        'download-dark': "url('/assets/icons/dark-download.svg')",
        'share1-light': "url('/assets/icons/light-share1.svg')",
        'share1-dark': "url('/assets/icons/dark-share1.svg')",
        'arrow-light': "url('/assets/icons/light-right-arrow.svg')",
        'arrow-dark': "url('/assets/icons/dark-right-arrow.svg')",
        'exit-light': "url('/assets/icons/light-exit.svg')",
        'exit-dark': "url('/assets/icons/dark-exit.svg')",
        'tiktok-medium-light': "url('/assets/icons/light-tiktok-medium.svg')",
        'tiktok-medium-dark': "url('/assets/icons/dark-tiktok -medium.svg')",
        'link-light': "url('/assets/icons/light-link.svg')",
        'link-dark': "url('/assets/icons/dark-link.svg')",
        'usermulti-light': "url('/assets/icons/light-usermulti.svg')",
        'usermulti-dark': "url('/assets/icons/dark-usermulti.svg')",
        'all-light': "url('/assets/icons/light-all.svg')",
        'all-dark': "url('/assets/icons/dark-all.svg')",
        'facebook-light': "url('/assets/icons/light-facebook.svg')",
        'facebook-dark': "url('/assets/icons/dark-facebook.svg')",
        'time-light': "url('/assets/icons/light-time.svg')",
        'time-dark': "url('/assets/icons/dark-time.svg')",
        'creation-light': "url('/assets/icons/light-creation.svg')",
        'creation-dark': "url('/assets/icons/dark-creation.svg')",
        'export-light': "url('/assets/icons/light-export.svg')",
        'export-dark': "url('/assets/icons/dark-export.svg')",
        'ranking-light': "url('/assets/icons/light-ranking.svg')",
        'ranking-dark': "url('/assets/icons/dark-ranking.svg')",
        'flag-canada': "url('/assets/flags/canada.png')",
        'website-light': "url('/assets/icons/light-website.svg')",
        'website-dark': "url('/assets/icons/dark-website.svg')",
        'light-card-impression': "url('/assets/icons/light-card-impression.svg')",
        'dark-card-impression': "url('/assets/icons/dark-card-impression.svg')",
        'light-card-like': "url('/assets/icons/light-card-like.svg')",
        'dark-card-like': "url('/assets/icons/dark-card-like.svg')",
        'light-card-number': "url('/assets/icons/light-card-number.svg')",
        'dark-card-number': "url('/assets/icons/dark-card-number.svg')",
        'light-card-sold': "url('/assets/icons/light-card-sold.svg')",
        'dark-card-sold': "url('/assets/icons/dark-card-sold.svg')",
        'light-card-cost': "url('/assets/icons/light-card-cost.svg')",
        'dark-card-cost': "url('/assets/icons/dark-card-cost.svg')",
        'light-card-sales': "url('/assets/icons/light-card-sales.svg')",
        'dark-card-sales': "url('/assets/icons/dark-card-sales.svg')",
        'light-card-product': "url('/assets/icons/light-card-product.svg')",
        'dark-card-product': "url('/assets/icons/dark-card-product.svg')",
        'add-light': "url('/assets/icons/light-add.svg')",
        'add-dark': "url('/assets/icons/dark-add.svg')",
        'details-light': "url('/assets/icons/light-details.svg')",
        'details-dark': "url('/assets/icons/dark-details.svg')",
        'collection-first-corner-light': "url('/assets/images/light-first-corner-image.png')",
        'collection-first-corner-dark': "url('/assets/images/dark-first-corner-image.png')",
        'collection-first-image-light': "url('/assets/images/light-first-image.png')",
        'collection-first-image-dark': "url('/assets/images/dark-first-image.png')",
        'collection-second-corner-light': "url('/assets/images/light-second-corner-image.png')",
        'collection-second-corner-dark': "url('/assets/images/dark-second-corner-image.png')",
        'collection-second-logo-light': "url('/assets/images/light-second-collection-logo.png')",
        'collection-second-logo-dark': "url('/assets/images/dark-second-collection-logo.png')",
        'collection-first-logo-light': "url('/assets/images/light-first-collection-logo.png')",
        'collection-first-logo-dark': "url('/assets/images/dark-first-collection-logo.png')",
        'collection-modal-icon-light': "url('/assets/icons/light-collection-modal-icon.svg')",
        'collection-modal-icon-dark': "url('/assets/icons/dark-collection-modal-icon.svg')",
        'collection-light-icon1': "url('/assets/icons/collections/collecton-light-icon1.png')",
        'collection-dark-icon1': "url('/assets/icons/collections/collecton-dark-icon1.png')",
        'collection-light-icon2': "url('/assets/icons/collections/collecton-light-icon2.png')",
        'collection-dark-icon2': "url('/assets/icons/collections/collecton-dark-icon2.png')",
        'collection-light-icon3': "url('/assets/icons/collections/collecton-light-icon3.png')",
        'collection-dark-icon3': "url('/assets/icons/collections/collecton-dark-icon3.png')",
        'collection-light-icon4': "url('/assets/icons/collections/collecton-light-icon4.png')",
        'collection-dark-icon4': "url('/assets/icons/collections/collecton-dark-icon4.png')",
        'collection-light-icon5': "url('/assets/icons/collections/collecton-light-icon5.png')",
        'collection-dark-icon5': "url('/assets/icons/collections/collecton-dark-icon5.png')",
        'collection-light-icon6': "url('/assets/icons/collections/collecton-light-icon6.png')",
        'collection-dark-icon6': "url('/assets/icons/collections/collecton-dark-icon6.png')",
        'collection-light-icon7': "url('/assets/icons/collections/collecton-light-icon7.png')",
        'collection-dark-icon7': "url('/assets/icons/collections/collecton-dark-icon7.png')",
        'collection-light-icon8': "url('/assets/icons/collections/collecton-light-icon8.png')",
        'collection-dark-icon8': "url('/assets/icons/collections/collecton-dark-icon8.png')",
        'collection-light-icon9': "url('/assets/icons/collections/collecton-light-icon9.png')",
        'collection-dark-icon9': "url('/assets/icons/collections/collecton-dark-icon9.png')",
        'collection-light-icon10': "url('/assets/icons/collections/collecton-light-icon10.png')",
        'collection-dark-icon10': "url('/assets/icons/collections/collecton-dark-icon10.png')",
        'collection-light-icon11': "url('/assets/icons/collections/collecton-light-icon11.png')",
        'collection-dark-icon11': "url('/assets/icons/collections/collecton-dark-icon11.png')",
        'collection-light-icon12': "url('/assets/icons/collections/collecton-light-icon12.png')",
        'collection-dark-icon12': "url('/assets/icons/collections/collecton-dark-icon12.png')",
        'collection-light-icon13': "url('/assets/icons/collections/collecton-light-icon13.png')",
        'collection-dark-icon13': "url('/assets/icons/collections/collecton-dark-icon13.png')",
        'collection-light-icon14': "url('/assets/icons/collections/collecton-light-icon14.png')",
        'collection-dark-icon14': "url('/assets/icons/collections/collecton-dark-icon14.png')",
        'collection-light-icon15': "url('/assets/icons/collections/collecton-light-icon15.png')",
        'collection-dark-icon15': "url('/assets/icons/collections/collecton-dark-icon15.png')",
        'collection-light-icon16': "url('/assets/icons/collections/collecton-light-icon16.png')",
        'collection-dark-icon16': "url('/assets/icons/collections/collecton-dark-icon16.png')",
        'collection-light-icon17': "url('/assets/icons/collections/collecton-light-icon17.png')",
        'collection-dark-icon17': "url('/assets/icons/collections/collecton-dark-icon17.png')",
        'collection-light-icon18': "url('/assets/icons/collections/collecton-light-icon18.png')",
        'collection-dark-icon18': "url('/assets/icons/collections/collecton-dark-icon18.png')",
        'collection-light-icon19': "url('/assets/icons/collections/collecton-light-icon19.png')",
        'collection-dark-icon19': "url('/assets/icons/collections/collecton-dark-icon19.png')",
        'theme-light-light': "url('/assets/icons/light-theme-light.svg')",
        'theme-light-dark': "url('/assets/icons/dark-theme-light.svg')",
        'theme-dark-light': "url('/assets/icons/light-theme-dark.svg')",
        'theme-dark-dark': "url('/assets/icons/dark-theme-dark.svg')",
        'theme-system-light': "url('/assets/icons/light-theme-system.svg')",
        'theme-system-dark': "url('/assets/icons/dark-theme-system.svg')",
        'hero-light-mode': "url('/images/landingpage/hero-light.png')",
        'hero-dark-mode': "url('/images/landingpage/hero-dark.png')",
      }),
      screens: {
        xss: '450px',
        xs: '550px',
        xxl: '1700px',
        xxxl: '1920px',
      },
      fontFamily: {
        holtwood: ['var(--font-holtwood)'],
        sans: ['var(--font-inter)'],
      },
      boxShadow: {
        social: '0 2px 10px -4px rgba(0,0,0,0.14)',
        'pricing-plan': '0 -2px 12px -2px rgba(0, 11, 167, 0.29)',
        modal: '0 10px 63.7px 0 rgba(0, 11, 167, 0.16)',
        card: '0 4px 15px -4px rgba(0, 0, 0, 0.07)',
      },
      spacing: {
        15: '60px',
      },
    },
  },
  plugins: [],
}
